version: '3'

services:
  api:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '3000:3000'

  redis:
    image: redis:bullseye
    restart: always
    ports:
      - "6379:6379"